dataset_name: imagenet 
input_dataset_path: /path/to/ILSVRC2012/ILSVRC2012_img_train/train
output_csv_path: ./out.csv
output_image_csv_path: ./out_image.csv
output_class_csv_path: ./out_classes.csv
normalize: false
